// 📜 STANDARDS 2026 REGULATORY FRAMEWORK
// Source-2026 / Circular VM-AC-2026

export const MEP_2026 = {
  // 1. EVALUATION RULES
  EVALUATION: {
    PASSING_GRADE: 70, // Standard
    MIN_ATTENDANCE: 80, // Percentage
    ALLOW_DRAGGING: false, // 🚫 NO ARRASTRE
    ALLOW_ADVANCEMENT: false, // 🚫 NO ADELANTO
    WRITING_TEST_REQUIRED: true, // 📝 PRUEBA DE ESCRITURA
  },

  // 2. CONDUCT CODES
  CONDUCT: {
    GRAVISIMAS: [
      "USO_VAPEO",
      "PORTACION_ARMAS",
      "CIBERBULLYING",
      "TRAFICO_SUSTANCIAS",
    ],
    GRAVES: [
      "USO_CELULAR_CLASE", // 📱 BANNED
      "INCUMPLIMIENTO_UNIFORME_REITERADO",
      "FALTA_RESPETO_DOCENTE",
    ],
    LEVES: ["LLEGADA_TARDIA", "SIN_MATERIALES", "INTERRUPCION_CLASE"],
  },

  // 3. DUA COMPLIANCE (Universal Design)
  DUA: {
    TAGS_REQUIRED: ["REPRESENTACION", "ACCION_EXPRESION", "MOTIVACION"],
    KEYWORDS: [
      "ELECCION",
      "MULTIFORMATO",
      "ACCESIBILIDAD",
      "LLUVIA_IDEAS",
      "GAMIFICACION",
      "VISUAL",
    ],
  },
};
